# Generated by Django 4.2.5 on 2023-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('P', 'P'), ('C', 'C'), ('IP', 'IP')], default='P', max_length=255),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='complete',
            field=models.BooleanField(default=False, max_length=255),
        ),
    ]
